#!/system/bin/sh
# detect.sh - Probe a rooted Android device for external-USB-Wi-Fi buildability.
#
# Reads the running kernel, checks whether its source commit is publicly
# buildable, inspects the kernel config, finds a plugged-in USB Wi-Fi adapter,
# and flags known blockers (module signing, SELinux, Unisoc watchdog). Emits a
# device-profile.txt you paste into the GitHub Actions build.
#
# It changes NOTHING on the device. Run it as root:
#   su
#   sh detect.sh
#
# Requires: curl with network access (Termux: pkg install curl).

OUT=./device-profile.txt
say() { echo "$*"; }
kv()  { printf '%-22s %s\n' "$1" "$2"; }

need_root() { [ "$(id -u)" = "0" ] && return 0; echo "Run as root (su)."; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# curl often lives only in Termux, not in the root PATH - add it
for p in /data/data/com.termux/files/usr/bin /system/bin /system/xbin; do
  case ":$PATH:" in *":$p:"*) ;; *) [ -d "$p" ] && PATH="$PATH:$p";; esac
done
export PATH
CURL=""
have curl && CURL=curl
[ -z "$CURL" ] && [ -x /data/data/com.termux/files/usr/bin/curl ] && CURL=/data/data/com.termux/files/usr/bin/curl

need_root
: > "$OUT"

say "=== android-gki-usb-wifi device probe ==="
say ""

# ---------------------------------------------------------------- kernel
KREL="$(uname -r)"
KVER="$(printf '%s' "$KREL" | cut -d- -f1)"      # e.g. 5.15.178
# short git hash is the gXXXXXXXX token in uname -r
KHASH="$(printf '%s' "$KREL" | tr '-' '\n' | grep -E '^g[0-9a-f]{7,}$' | head -1 | sed 's/^g//')"
# android branch token, e.g. android13
KBRANCH="$(printf '%s' "$KREL" | tr '-' '\n' | grep -E '^android[0-9]+$' | head -1)"
KGEN="${KBRANCH}-${KVER%.*}.${KVER##*.}"          # rough; refined below

kv "kernel_release" "$KREL"
kv "kernel_version" "$KVER"
kv "commit_short"   "${KHASH:-<none found>}"
kv "android_branch" "${KBRANCH:-<unknown>}"

# guess the ACK branch (android13-5.15 style) and flag pre-GKI kernels
MAJMIN="$(printf '%s' "$KVER" | cut -d. -f1,2)"   # e.g. 5.15
KMAJ="${MAJMIN%%.*}"; KMIN="${MAJMIN##*.}"
IS_GKI=yes
if [ "$KMAJ" -lt 5 ] 2>/dev/null; then IS_GKI=no; fi
if [ "$KMAJ" -eq 5 ] 2>/dev/null && [ "$KMIN" -lt 10 ] 2>/dev/null; then IS_GKI=no; fi
if [ -n "$KBRANCH" ]; then
  ACK_BRANCH="${KBRANCH}-${MAJMIN}"
else
  ACK_BRANCH="unknown (no androidNN token in uname -r)"
fi
kv "gki_kernel"       "$IS_GKI  (GKI starts at 5.10; yours is $MAJMIN)"
kv "ack_branch_guess" "$ACK_BRANCH"

{
  echo "# device-profile.txt - generated by detect.sh"
  echo "KERNEL_RELEASE=$KREL"
  echo "KERNEL_VERSION=$KVER"
  echo "COMMIT_SHORT=${KHASH}"
  echo "ANDROID_BRANCH=${KBRANCH}"
  echo "ACK_BRANCH_GUESS=${ACK_BRANCH}"
  echo "KERNEL_GEN=${ACK_BRANCH}"
  echo "IS_GKI=${IS_GKI}"
} >> "$OUT"

say ""

# ---------------------------------------------------------- commit public?
COMMIT_OK=no
FULLHASH=""
if [ -n "$KHASH" ] && [ -n "$CURL" ]; then
  say "Checking whether the kernel commit is public on ACK..."
  # gitiles accepts the short hash; a 200 means it exists in kernel/common
  CODE="$($CURL -s -o /dev/null -w '%{http_code}' \
     "https://android.googlesource.com/kernel/common/+/$KHASH" 2>/dev/null)"
  if [ "$CODE" = "200" ]; then
    COMMIT_OK=yes
    kv "commit_public" "YES (HTTP 200) - buildable from this commit"
  else
    kv "commit_public" "NO (HTTP $CODE) - see notes below"
  fi
else
  kv "commit_public" "SKIPPED (no curl or no hash)"
fi
echo "COMMIT_PUBLIC=$COMMIT_OK" >> "$OUT"
say ""

# --------------------------------------------------------------- config
CFG=/proc/config.gz
getcfg() { zcat "$CFG" 2>/dev/null | grep -E "^$1=" | head -1; }
has_y()  { zcat "$CFG" 2>/dev/null | grep -qE "^$1=y"; }

if zcat "$CFG" >/dev/null 2>&1; then
  MODVER=$(has_y CONFIG_MODVERSIONS && echo y || echo n)
  BTF=$(has_y CONFIG_DEBUG_INFO_BTF && echo y || echo n)
  LTOFULL=$(has_y CONFIG_LTO_CLANG_FULL && echo y || echo n)
  LTOTHIN=$(has_y CONFIG_LTO_CLANG_THIN && echo y || echo n)
  MODULES=$(has_y CONFIG_MODULES && echo y || echo n)
  SIG=$(has_y CONFIG_MODULE_SIG_FORCE && echo y || echo n)
  kv "CONFIG_MODULES"        "$MODULES"
  kv "CONFIG_MODVERSIONS"    "$MODVER"
  kv "CONFIG_DEBUG_INFO_BTF" "$BTF"
  kv "LTO_CLANG_FULL/THIN"   "$LTOFULL / $LTOTHIN"
  kv "MODULE_SIG_FORCE"      "$SIG"
  {
    echo "CONFIG_MODULES=$MODULES"
    echo "CONFIG_MODVERSIONS=$MODVER"
    echo "CONFIG_DEBUG_INFO_BTF=$BTF"
    echo "LTO_FULL=$LTOFULL"
    echo "LTO_THIN=$LTOTHIN"
    echo "MODULE_SIG_FORCE=$SIG"
  } >> "$OUT"
else
  kv "config.gz" "NOT READABLE - cannot verify BTF/LTO (build may mismatch)"
  echo "CONFIG_READABLE=no" >> "$OUT"
  MODULES=?; MODVER=?; BTF=?; LTOFULL=?; SIG=?
fi
say ""

# ------------------------------------------------------------ USB adapter
# Known USB IDs -> module + firmware hints
usb_hint() {
  # returns: driver|firmware|description
  case "$1" in
    # --- MediaTek (in-tree mt76) ---
    0e8d:7612) echo "mt76x2u|mt7662.bin,mt7662_rom_patch.bin|MT7612U (ALFA AWUS036ACM)";;
    0e8d:7662) echo "mt76x2u|mt7662.bin,mt7662_rom_patch.bin|MT7612U";;
    0b05:17d2) echo "mt76x2u|mt7662.bin,mt7662_rom_patch.bin|MT7612U (Asus USB-AC53)";;
    057c:8503) echo "mt76x2u|mt7662.bin,mt7662_rom_patch.bin|MT7612U (AVM FRITZ AC860)";;
    0e8d:7610) echo "mt76x0u|mt7610u.bin|MT7610U";;
    # --- MediaTek MT7601U (separate in-tree driver, not part of mt76) ---
    148f:7601) echo "mt7601u|mt7601u.bin|MT7601U (very common cheap 2.4GHz dongle)";;
    148f:760a) echo "mt7601u|mt7601u.bin|MT7601U";;
    148f:760c) echo "mt7601u|mt7601u.bin|MT7601U";;
    2717:4106) echo "mt7601u|mt7601u.bin|MT7601U (Xiaomi)";;
    # --- adapters that boot in CD-ROM/driver-install mode ---
    0bda:1a2b) echo "usb_modeswitch|n/a|Realtek in CD-ROM mode - run usb_modeswitch first, then re-run detect";;
    0bda:1f01) echo "usb_modeswitch|n/a|Realtek in CD-ROM mode - run usb_modeswitch first, then re-run detect";;
    148f:761a) echo "mt76x0u|mt7610u.bin|MT7610U (Ralink-branded)";;
    148f:760b) echo "mt76x0u|mt7610u.bin|MT7610U";;
    0e8d:7630) echo "mt76x0u|mt7610u.bin|MT7630U";;
    0e8d:7650) echo "mt76x0u|mt7650u.bin|MT7650U";;
    # --- Ralink / MediaTek legacy (in-tree rt2800usb) ---
    148f:5370) echo "rt2800usb|none|RT5370 (very common cheap dongle)";;
    148f:5372) echo "rt2800usb|none|RT5372";;
    148f:3070) echo "rt2800usb|none|RT3070";;
    148f:3072) echo "rt2800usb|none|RT3072";;
    148f:2870) echo "rt2800usb|none|RT2870";;
    148f:3572) echo "rt2800usb|none|RT3572";;
    0b05:1732) echo "rt2800usb|none|RT2870 (Asus WL-167g)";;
    07d1:3c09) echo "rt2800usb|none|RT2870 (D-Link DWA-140)";;
    2001:3c1e) echo "rt2800usb|none|RT5372 (D-Link)";;
    # --- Atheros (in-tree ath9k_htc) ---
    0cf3:9271) echo "ath9k_htc|htc_9271.fw|AR9271 (ALFA AWUS036NHA)";;
    0cf3:1006) echo "ath9k_htc|htc_9271.fw|AR9271";;
    0846:9030) echo "ath9k_htc|htc_9271.fw|AR9271 (Netgear WNA1100)";;
    040d:3801) echo "ath9k_htc|htc_9271.fw|AR9271";;
    13b1:0031) echo "ath9k_htc|htc_9271.fw|AR9271 (Linksys AE1000)";;
    0cf3:7015) echo "ath9k_htc|htc_7010.fw|AR7010 (AR9280/9287 dual-band)";;
    0846:9018) echo "ath9k_htc|htc_7010.fw|AR7010 (Netgear WNDA3200)";;
    083a:a704) echo "ath9k_htc|htc_7010.fw|AR7010 (ZyXEL)";;
    # --- Realtek in-tree (rtl8xxxu) : RTL8188/8192 CU/EU/RU ---
    0bda:8176) echo "rtl8xxxu|none|RTL8188CU";;
    0bda:8178) echo "rtl8xxxu|none|RTL8192CU";;
    0bda:817a) echo "rtl8xxxu|none|RTL8188CU";;
    0bda:818b) echo "rtl8xxxu|none|RTL8192EU";;
    0bda:8179) echo "rtl8xxxu|none|RTL8188EU";;
    2001:330d) echo "rtl8xxxu|none|RTL8192CU (D-Link DWA-131)";;
    0bda:8172) echo "rtl8xxxu|none|RTL8191SU";;
    # --- Realtek OUT-OF-TREE (rtl88xxau_oot) : RTL8812/8814/8821 AU ---
    0bda:8812) echo "rtl88xxau_oot|none(in-driver)|RTL8812AU (ALFA AWUS036ACH; OUT-OF-TREE driver)";;
    0bda:881a) echo "rtl88xxau_oot|none(in-driver)|RTL8812AU (OUT-OF-TREE)";;
    0bda:8813) echo "rtl88xxau_oot|none(in-driver)|RTL8814AU (ALFA AWUS1900; OUT-OF-TREE)";;
    0bda:8811) echo "rtl88xxau_oot|none(in-driver)|RTL8811AU (OUT-OF-TREE)";;
    0bda:0811) echo "rtl88xxau_oot|none(in-driver)|RTL8811AU (OUT-OF-TREE)";;
    2357:0108) echo "rtl88xxau_oot|none(in-driver)|RTL8812AU (TP-Link Archer T4U; OUT-OF-TREE)";;
    2357:0101) echo "rtl88xxau_oot|none(in-driver)|RTL8812AU (TP-Link; OUT-OF-TREE)";;
    0e66:0022) echo "rtl88xxau_oot|none(in-driver)|RTL8812AU (Hawking; OUT-OF-TREE)";;
    # --- Realtek OUT-OF-TREE (rtl8821cu_oot) : RTL8811CU/8821CU (morrownr driver) ---
    0bda:c820) echo "rtl8821cu_oot|none(in-driver)|RTL8821CU (TP-Link Archer T2U Nano / T2UB Nano / T2U Plus; OUT-OF-TREE)";;
    0bda:c811) echo "rtl8821cu_oot|none(in-driver)|RTL8811CU (OUT-OF-TREE)";;
    0bda:c82c) echo "rtl8821cu_oot|none(in-driver)|RTL8821CU (OUT-OF-TREE)";;
    2357:012d) echo "rtl8821cu_oot|none(in-driver)|RTL8821CU (TP-Link Archer T2U Plus; OUT-OF-TREE)";;
    2357:0138) echo "rtl8821cu_oot|none(in-driver)|RTL8821CU (TP-Link Archer T2U Nano; OUT-OF-TREE)";;
    *) echo "unknown|unknown|unrecognized - look up the USB ID";;
  esac
}

FOUND=""
for d in /sys/bus/usb/devices/*/idProduct; do
  dir=$(dirname "$d"); [ -f "$dir/idVendor" ] || continue
  id="$(cat "$dir/idVendor"):$(cat "$d")"
  # skip hubs/root
  cls=$(cat "$dir/bDeviceClass" 2>/dev/null)
  [ "$cls" = "09" ] && continue
  hint=$(usb_hint "$id")
  drv=$(printf '%s' "$hint" | cut -d'|' -f1)
  fw=$(printf '%s'  "$hint" | cut -d'|' -f2)
  desc=$(printf '%s' "$hint" | cut -d'|' -f3)
  # only report likely wifi (known ids, or has a wireless-ish interface)
  case "$id" in
    0e8d:*|0bda:*|148f:*|0cf3:*|0846:*|2717:*|0b05:*|057c:*|07d1:*|2001:*|2357:*|040d:*|13b1:*|083a:*|0e66:*|040d:*)
      FOUND="$id"
      USB_ID_FOUND="$id"
      CHIPSET_DESC="$desc"
      kv "usb_wifi_found" "$id at $(basename "$dir")"
      kv "  chipset"      "$desc"
      kv "  driver"       "$drv"
      kv "  firmware"     "$fw"
      {
        echo "USB_ID=$id"
        echo "USB_PATH=$(basename "$dir")"
        echo "DRIVER=$drv"
        echo "FIRMWARE=$fw"
        echo "CHIPSET=$desc"
      } >> "$OUT"
      ;;
  esac
done
[ -z "$FOUND" ] && { kv "usb_wifi_found" "none (plug the adapter in and re-run)"; echo "USB_ID=" >> "$OUT"; }
say ""

# ---------------------------------------------------------- environment
SEL=$(getenforce 2>/dev/null || echo unknown)
kv "selinux" "$SEL"
echo "SELINUX=$SEL" >> "$OUT"

WD=no
lsmod 2>/dev/null | grep -qi native_hang_monitor && WD=yes
kv "unisoc_watchdog" "$WD  (native_hang_monitor; needs autoprobe-off load trick)"
echo "UNISOC_WATCHDOG=$WD" >> "$OUT"

# is this the known-good reference platform?
REF=no
printf '%s' "$KREL" | grep -q "g4ea0fcb5d130" && REF=yes
kv "known_good_ums9230" "$REF"
echo "KNOWN_GOOD_UMS9230=$REF" >> "$OUT"
say ""

# ------------------------------------------------------------- verdict
say "=== VERDICT ==="
BLOCK=0
if [ "$IS_GKI" = "no" ]; then
  say "NOT GKI: kernel $KVER predates the Generic Kernel Image (5.10+)."
  say "  The automated workflow targets ACK/GKI kernels, so it cannot fetch"
  say "  matching source for you. You are NOT out of options:"
  say "   - First check if your kernel ALREADY supports the adapter:"
  say "       plug it in, then run:  ip link    (look for wlan1)"
  say "   - If you run a CUSTOM kernel, its source is usually published (GPL)."
  say "     Build the driver as an external module against THAT source, or ask"
  say "     its maintainer to enable it. Many 4.x pentest kernels already do."
  BLOCK=1
fi
[ "$MODULES" = "n" ] && { say "BLOCKER: CONFIG_MODULES=n - kernel cannot load modules at all."; BLOCK=1; }
[ "$SIG" = "y" ]     && { say "BLOCKER: MODULE_SIG_FORCE=y - unsigned modules will be rejected."; BLOCK=1; }
if [ "$REF" = "yes" ] && [ "$COMMIT_OK" != "yes" ]; then
  COMMIT_OK=yes   # known-good reference: commit is public (verified 4ea0fcb5d130)
fi
[ "$COMMIT_OK" = "no" ] && [ -n "$KHASH" ] && say "WARNING: kernel commit not confirmed public - if the build's module_layout CRC differs from yours, you must locate matching source (vendor GPL drop)."
[ -z "$KHASH" ] && say "NOTE: no git hash in uname -r (typical for custom kernels) - the exact source cannot be identified automatically."
[ "$MODVER" = "y" ] && say "NOTE: MODVERSIONS=y - modules MUST be built from the exact commit (this is normal for GKI)."
[ "$BTF" = "y" ] && say "NOTE: BTF=y - build must keep BTF enabled (workflow installs pahole)."
[ "$LTOTHIN" = "y" ] && say "NOTE: thin LTO in use - set LTO thin in the workflow to match."
case "${DRIVER:-}" in
  rtl88xxau_oot)
    say "NOTE: this adapter needs an OUT-OF-TREE Realtek driver (RTL8812/8814/8821AU)."
    say "      The workflow builds it from an external repo (default: aircrack-ng/rtl8812au)."
    say "      Success is less guaranteed than in-tree drivers; the driver must support"
    say "      your kernel version. If it fails to build, try a different driver branch." ;;
  rtl8821cu_oot)
    say "NOTE: this adapter needs an OUT-OF-TREE Realtek driver (RTL8811CU/8821CU)."
    say "      The workflow builds it from morrownr/8821cu-20210916 against your kernel."
    say "      Monitor mode is supported; injection on the CU chip is weaker than AU -"
    say "      verify with 'aireplay-ng --test wlan1'. If the build fails, try oot_branch." ;;
  rtl8xxxu)
    say "NOTE: RTL8188/8192 via in-tree rtl8xxxu. Monitor-mode/injection support varies by chip." ;;
  rt2800usb)
    say "NOTE: rt2800usb has good monitor/injection support and needs no firmware file." ;;
  mt7601u)
    say "NOTE: MT7601U uses the in-tree 'mt7601u' driver (separate from the mt76 stack)."
    say "      2.4GHz only. Monitor mode works; injection support is limited on some units." ;;
  usb_modeswitch)
    say "NOTE: this adapter is in CD-ROM / driver-install mode, not Wi-Fi mode yet."
    say "      Switch it first, e.g.:  usb_modeswitch -KW -v <vid> -p <pid>"
    say "      (or 'eject /dev/sr0' on some units), then re-run detect.sh." ;;
esac

if [ "$REF" = "yes" ]; then
  say ""
  say "FAST PATH: this is the known-good UMS9230/T615 reference kernel."
  say "You can use the default workflow inputs as-is."
elif [ "$BLOCK" = "0" ]; then
  say ""
  say "LIKELY BUILDABLE (best-effort). Use device-profile.txt values as workflow inputs."
else
  say ""
  say "NOT BUILDABLE as-is (see BLOCKER lines above)."
fi

say ""
say "Wrote $OUT - paste its values into the GitHub Actions 'Run workflow' inputs."

# ---------------------------------------------------- share your result
# Opt-in, zero telemetry: we do NOT send anything. We only PRINT a pre-filled
# GitHub issue link. You open it, review exactly what it contains, and submit it
# yourself (or don't). This is how the community compatibility list grows.
urlenc() {
  # minimal urlencode for the short fields
  printf '%s' "$1" | sed -e 's|%|%25|g' -e 's| |%20|g' -e 's|/|%2F|g' \
      -e 's|(|%28|g' -e 's|)|%29|g' -e 's|:|%3A|g' -e 's|&|%26|g' \
      -e 's|+|%2B|g' -e 's|#|%23|g' -e 's|,|%2C|g'
}

REPO_URL="https://github.com/markatsos/android-gki-usb-wifi"
say ""
say "=== SHARE YOUR RESULT (optional) ==="
say "Nothing is sent automatically. If you'd like to add your device to the"
say "public compatibility list, open this link, check the pre-filled fields,"
say "paste the output above into the last box, and submit:"
say ""
DEV_Q=$(urlenc "${KREL%%-*} device - fill in model/SoC")
KER_Q=$(urlenc "$KREL")
ADP_Q=$(urlenc "${USB_ID_FOUND:-unknown} ${CHIPSET_DESC:-}")
say "$REPO_URL/issues/new?template=compatibility.yml&kernel=$KER_Q&adapter=$ADP_Q"
say ""
say "(Your device-profile.txt is at: $OUT)"
